#!/usr/bin/env node

import process from "node:process";

import {main} from "./pleo-expense.mjs";

main().catch((error) => {
  process.stderr.write(`${error.message}\n`);
  process.exitCode = 1;
});
